# Generated by Django 3.2.16 on 2023-04-14 07:41

import autoslug.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('Image', models.ImageField(blank=True, default='media/category/blank.png', null=True, upload_to='media/category')),
                ('delete_status', models.CharField(choices=[('deleted', 'deleted'), ('not deleted', 'not deleted')], default='not deleted', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(max_length=10)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Main_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('delete_status', models.CharField(choices=[('deleted', 'deleted'), ('not deleted', 'not deleted')], default='not deleted', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='latest_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Most Read', 'Most Read'), ('Trending', 'Trending')], default='New', max_length=200)),
                ('show_front', models.CharField(choices=[('Show', 'Show'), ('Dont Show', 'Dont Show')], default='Show', max_length=200)),
                ('delete_status', models.CharField(choices=[('deleted', 'deleted'), ('not deleted', 'not deleted')], default='not deleted', max_length=200)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/')),
                ('details', models.TextField(blank=True, null=True)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/')),
                ('img2_details', models.TextField(blank=True, null=True)),
                ('Image_3', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/')),
                ('img3_details', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
                ('meta_title', models.CharField(blank=True, max_length=120, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=120, null=True)),
                ('meta_keyword', models.CharField(max_length=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.main_category'),
        ),
    ]
