# Generated by Django 3.2.16 on 2023-04-19 08:20

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_news',
            name='meta_keyword',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
