# Generated by Django 4.2 on 2023-04-19 09:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20230419_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_news',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='latest_news',
            name='img2_details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='latest_news',
            name='img3_details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
