# Generated by Django 3.2.16 on 2023-07-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_latest_news_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_news',
            name='meta_keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
